Repository thoth-station/si-bandit, pull requests merged in 2020-09, with the labels that each got.

#28 Automatic update of dependency thoth-common from 0.14.2 to 0.18.2
  Pipfile.lock
Labels: approved, bot, size/L

#30 Release of version 0.1.4
  CHANGELOG.md
  thoth/si_bandit/version.py
Labels: approved, bot, size/XS

#29 Automatic update of dependency thoth-python from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: approved, bot, size/XS

#32 Automatic update of dependency thoth-common from 0.18.2 to 0.18.3
  Pipfile.lock
Labels: approved, bot, size/S

#33 Add version logs
  app.py
Labels: approved

#37 Make pre-commit happy
  app.py
Labels: approved, size/XS

#35 Automatic update of dependency thoth-common from 0.18.3 to 0.19.0
  Pipfile.lock
Labels: approved, bot, size/S
