Repository thoth-station/si-bandit, pull requests merged in 2020-06, with the labels that each got.

#3 add pre-commit config
  .pre-commit-config.yaml
Labels: approved, size/M

#5 Added readme commands
  README.md
Labels: approved, size/S

#4 Oc argo templates
  .coafile
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
  .github/PULL_REQUEST_TEMPLATE.md
  .pre-commit-config.yaml
  app.sh
  openshift/buildConfig.yaml
  openshift/imageStream-template.yaml
  openshift/si-bandit-template.yaml
  thoth/si_bandit/__init__.py
  thoth/si_bandit/cli.py
  workflows/templates/bandit-template.yaml
Labels: approved, size/L

#10 Release time
  Pipfile
  Pipfile.lock
  openshift/buildConfig.yaml
  openshift/imageStream-template.yaml
  openshift/si-bandit-template.yaml
  thoth/si_bandit/cli.py
  workflows/templates/bandit-template.yaml
Labels: approved, size/L

#12 Automatic update of dependency thoth-common from 0.13.12 to 0.13.13
  Pipfile.lock
Labels: approved, bot, size/M
