Repository thoth-station/si-bandit, pull requests merged in 2020-07, with the labels that each got.

#13 Fix bandit version
  Pipfile
  Pipfile.lock
Labels: approved, size/S

#14 now part of thoth-application
  openshift/buildConfig.yaml
  openshift/imageStream-template.yaml
  openshift/si-bandit-template.yaml
Labels: approved, size/L

#17 Release of version 0.1.1
  CHANGELOG.md
  thoth/si_bandit/version.py
Labels: approved, bot, size/M

#16 Automatic update of dependency thoth-common from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: approved, bot, size/L

#19 Release of version 0.1.2
  CHANGELOG.md
  thoth/si_bandit/version.py
Labels: approved, bot, size/M

#21 include aicoe-ci configuration file
  .aicoe-ci.yaml
  .thoth.yaml
  .zuul.yaml
  workflows/templates/bandit-template.yaml
Labels: approved, size/M

#22 Move cli to be in toplevel dir
  app.py
  app.sh
  si-bandit
Labels: approved, size/XS

#24 Release of version 0.1.3
  CHANGELOG.md
  thoth/si_bandit/version.py
Labels: approved, bot, size/XS
